#!/usr/bin/env bash

set -exuo pipefail

OPENSIM_HOME="${OPENSIM_HOME:-${PWD}/opensim-core}"
CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"
NUM_BUILD_JOBS="${NUM_BUILD_JOBS:-$(nproc)}"
PROJECT_DIR="${PWD}"

set -x
git submodule update --init --recursive
mkdir -p build/

cd build/
set +x

cmake ../ \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE=TRUE \
      -DCMAKE_INSTALL_PREFIX="${PROJECT_DIR}/install" \
      -DOPENSIM_INSTALL_DIR="${OPENSIM_HOME}" \
      -DOPENSIM_INCLUDE_DIR="${OPENSIM_HOME}/sdk/include"

make "-j${NUM_BUILD_JOBS}"
