#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/linux_config  # sets relevant envvar defaults

echo "${0}: building opensim3"

mkdir -p "${OPENSIM3_INSTALL_PATH}"
mkdir -p opensim3-scone/build
cd opensim3-scone/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DSIMBODY_HOME="${SIMBODY_INSTALL_PATH}" \
      -DCMAKE_INSTALL_PREFIX="${OPENSIM3_INSTALL_PATH}"
make -j${NUM_BUILD_JOBS}
make install
cd -
