#!/usr/bin/env bash

set -exuo pipefail

OPENSIM_HOME="${OPENSIM_HOME:-${PWD}/opensim-core}"
CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"
NUM_BUILD_JOBS="${NUM_BUILD_JOBS:-$(nproc)}"
PROJECT_DIR="${PWD}"

cd build/
set +x
cmake ../ \
    -DOSG_DIR="${PROJECT_DIR}/OpenSceneGraph-3.4" \
    -DCMAKE_PREFIX_PATH="${PROJECT_DIR}/OpenSceneGraph-3.4/lib64" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_VERBOSE_MAKEFILE=TRUE \
    -DCMAKE_INSTALL_PREFIX="${PROJECT_DIR}/install" \
    -DOPENSIM_INSTALL_DIR="${OPENSIM_HOME}" \
    -DOPENSIM_INCLUDE_DIR="${OPENSIM_HOME}/sdk/include"

make "-j${NUM_BUILD_JOBS}"
