#!/usr/bin/env bash

# Bundles the SconeStudio.app/ directory created by the dirtree step into a
# single `.dmg` file that users can download + install easily
#
# Requires `create-dmg` to bundle the dir up

set -xeuo pipefail
source ./tools/build_config

# create-dmg fails if target already exists
rm -f "${SCONE_BUILD_DIR}/SconeStudio.dmg"

./create-dmg/create-dmg \
    --volicon "${SCONE_BUILD_DIR}/SconeStudio.app/Contents/MacOS/resources/ui/scone_logo_256x256.icns" \
    --volname "sconestudio installer" \
    --icon "${SCONE_BUILD_DIR}/SconeStudio.app" 0 0 \
    --icon-size 100 \
    --app-drop-link 200 0 \
    "${SCONE_BUILD_DIR}/SconeStudio.dmg" \
    "${SCONE_BUILD_DIR}/SconeStudio.app"

