#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config

echo "${0}: building openscenegraph"

mkdir -p "${OSG_INSTALL_PATH}"
mkdir -p OpenSceneGraph/build
cd OpenSceneGraph/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DUSE_RPATH=OFF \
      -DCMAKE_INSTALL_PREFIX="${OSG_INSTALL_PATH}" \
      -DOSG_USE_QT=ON \
      -DDESIRED_QT_VERSION=5 \
      -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
      -DCMAKE_PREFIX_PATH="${QT5_BREW_PATH}/lib/cmake/Qt5Widgets/"
cmake --build . --parallel "${NUM_BUILD_JOBS}" --target install
cd -
