#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/linux_config  # sets relevant envvar defaults

mkdir -p "${SCONE_BUILD_DIR}"
mkdir -p "${SCONE_INSTALL_DIR}"
cd "${SCONE_BUILD_DIR}"
cmake ../ \
    -DOSG_DIR="${OSG_INSTALL_PATH}" \
    -DCMAKE_PREFIX_PATH="${OSG_INSTALL_PATH}/lib64;/usr/local/Cellar/qt/5.15.0" \
    -DOSGQT_INCLUDE_DIR="${OSG_INSTALL_PATH}/lib64" \
    -DOSGQT_LIBRARY_RELEASE="${OSG_INSTALL_PATH}/lib/libosgQt.dylib" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
    -DCMAKE_INSTALL_PREFIX="${SCONE_INSTALL_DIR}" \
    -DOPENSIM_INSTALL_DIR="${OPENSIM3_INSTALL_PATH}" \
    -DOPENSIM_INCLUDE_DIR="${OPENSIM3_INSTALL_PATH}/sdk/include"
make -j${NUM_BUILD_JOBS}
cd -
