#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config  # sets relevant envvar defaults

echo "${0}: building opensim3"

mkdir -p "${OPENSIM3_INSTALL_PATH}"
mkdir -p opensim3-scone/build
cd opensim3-scone/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DSIMBODY_HOME="${SIMBODY_INSTALL_PATH}" \
      -DCMAKE_INSTALL_PREFIX="${OPENSIM3_INSTALL_PATH}" \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10
 #     -DCMAKE_CXX_FLAGS="-stdlib=libc++"
make -j${NUM_BUILD_JOBS}
make install
# TODO: chmod +x opensim3-scone/install/lib/*.dylib
cd -
