#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config

if [[ "$OSTYPE" == "darwin"* ]]; then
    cmake_extra_args=(
        -DCMAKE_PREFIX_PATH="${OSG_INSTALL_PATH}/lib64;${QT5_BREW_PATH}"
        -DOSGQT_INCLUDE_DIR="${OSG_INSTALL_PATH}/lib64"
        -DOSGQT_LIBRARY_RELEASE="${OSG_INSTALL_PATH}/lib/libosgQt.dylib"
        -DSCONE_SCONESTUDIO_REQUIRED=ON
    )
else
    cmake_extra_args=(
        -DCMAKE_PREFIX_PATH="${OSG_INSTALL_PATH}/lib64"
        -DSCONE_LUA=ON
   )
fi

mkdir -p "${SCONE_BUILD_DIR}"
mkdir -p "${SCONE_INSTALL_DIR}"
cd "${SCONE_BUILD_DIR}"
cmake ../ \
    -DOSG_DIR="${OSG_INSTALL_PATH}" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
    -DCMAKE_INSTALL_PREFIX="${SCONE_INSTALL_DIR}" \
    -DOPENSIM_INSTALL_DIR="${OPENSIM3_INSTALL_PATH}" \
    -DOPENSIM_INCLUDE_DIR="${OPENSIM3_INSTALL_PATH}/sdk/include" \
    ${cmake_extra_args[@]}
cmake --build . --parallel "${NUM_BUILD_JOBS}"
