#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config

# setup platform-specific build flags
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM_SPECIFIC_FLAGS=(
        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10
        -DCMAKE_CXX_FLAGS="-stdlib=libc++"
    )
else
    PLATFORM_SPECIFIC_FLAGS=(
    )
fi

echo "${0}: building opensim3"

mkdir -p "${OPENSIM3_INSTALL_PATH}"
mkdir -p opensim3-scone/build
cd opensim3-scone/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DSIMBODY_HOME="${SIMBODY_INSTALL_PATH}" \
      -DCMAKE_INSTALL_PREFIX="${OPENSIM3_INSTALL_PATH}" \
      ${PLATFORM_SPECIFIC_FLAGS[@]}
cmake --build . --parallel ${NUM_BUILD_JOBS} --target install
cd -
