#!/usr/bin/env bash

set -xeuo pipefail
source ./tools/build_config

if [[ "$OSTYPE" == "darwin"* ]]; then
    cmake_extra_flags=(
        # otherwise, loads of OpenGL deprecation warnings
        -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations"

        # because brew-installed qt5 isn't on the search path
        -DCMAKE_PREFIX_PATH="${QT5_BREW_PATH}/lib/cmake/Qt5Widgets/"
    )
else
    cmake_extra_flags=(
    )
fi

echo "${0}: building openscenegraph"

mkdir -p "${OSG_INSTALL_PATH}"
mkdir -p OpenSceneGraph/build
cd OpenSceneGraph/build
cmake .. \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
      -DUSE_RPATH=OFF \
      -DCMAKE_INSTALL_PREFIX="${OSG_INSTALL_PATH}" \
      -DOSG_USE_QT=ON \
      -DDESIRED_QT_VERSION=5 \
      ${cmake_extra_flags[@]}
cmake \
    --build . \
    --parallel "${NUM_BUILD_JOBS}" \
    --target install

# HACK: on linux, also package libpng, because the version
#       can change in package managers
if [[ "$OSTYPE" != "darwin"* ]]; then
    cp /usr/lib/x86_64-linux-gnu/libpng16.so "${OSG_INSTALL_PATH}/lib64/"
    chmod 755 "${OSG_INSTALL_PATH}/lib64/libpng16.so"
    cd -
fi

